### ISSUE TITLE
Protect Routes with specific user roles - middleware

### ISSUE THREAD

**Issue by Nicanor008** [Nicanor008/shoman-api#5]
## Available Roles/users
- Admin
- mentor
- mentee
- user(read-only)

## Example
router.route('/mentor/project').post(isMentor, Controller)
`isMentor` will be the user role middleware to be called to indicate this endpoint is only accessible by a mentor and gives an error for other user.

**Comment by Nyakaru** [comment]
This is in order.

**Comment by Nyakaru** [comment]
This is done
